name: CI/CD Flow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  CSV_URL: "MLProject/energy_preprocessed.csv"
  TARGET_VAR: "EnergyConsumption"

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.7

      - name: Install dependencies
        run: |
          pip install mlflow pandas numpy scikit-learn
      
      - name: Start MLflow server
        run: |
          mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./artifacts --host 0.0.0.0 --port 5000 &
          sleep 5
      
      - name: Run modeling.py
        run: |
          python MLProject/modeling.py --csv_url ${{ env.CSV_URL }} --target_var ${{ env.TARGET_VAR }}

      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(mlflow runs list --experiment-name "Energy Consumption Predictions" | awk 'NR==2{print $1}')
          echo "Last run_id: $RUN_ID"
