name: CI/CD Flow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  CSV_URL: "energy_preprocessed.csv"
  TARGET_VAR: "EnergyConsumption"

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
          - name: Run actions/checkout@v3
            uses: actions/checkout@v3

          - name: Set up Python 3.12.7
            uses: actions/setup-python@v4
            with:
              python-version: "3.12.7"

          - name: Check Env
            run: |
              echo $CSV_URL

          - name: Install Dependencies
            run: |
              python -m pip install --upgrade pip
              pip install mlflow seaborn matplotlib scikit-learn pandas numpy

          - name: Run MLFlow Project
            run: |
              mlflow run MLProject --env-manager=local

          - name: Get latest MLFlow run_id
            run: |
              RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
              echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
              echo "Latest run_id: $RUN_ID"
